# Change type: Editor configuration
'type: editor':
- .editorconfig
- .ccls

# Change type: Repo's license
'type: license':
- LICENSE

# Change type: Visual Studio solution/project
'type: visual studio':
- 'Athena.sln'
- '**/**/*.vcxproj'
- '**/**/*.vcxproj.filters'

# Change type: CMake configuration
'type: cmake':
- CMakeLists.txt
- '**/CMakeLists.txt'

# Change type: C++ Code
'type: c++':
- '**/*.cpp'
- '**/*.hpp'

# Change type: Github Actions workflows
'type: workflows':
- LICENSE